"""user auth columns

Revision ID: 8208e7694462
Revises: 01135281e9f4
Create Date: 2026-07-10 12:49:02.484495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # maluS: autogenerated columns may use sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '8208e7694462'
down_revision: Union[str, Sequence[str], None] = '01135281e9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so existing rows get False when the column is added; the
    # ORM default (False) governs new rows written by the app.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('is_ai', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column(
                'must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('is_ai')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
